name: pocket_guard_flutter_app
description: App to track your finance state
publish_to: 'none'
version: 0.0.1

environment:
    sdk: '>=3.0.1 <4.0.0'

dependencies:
    flutter:
        sdk: flutter

    # Internationalization
    flutter_localizations:
        sdk: flutter
    intl: any

    # Logger
    logger: ^1.4.0

    # Splash screen
    app_runner: ^2.2.0+1

    # Local data storage
    flutter_secure_storage: ^8.0.0

    # Network and internet
    dio: ^5.2.1+1
    connectivity_plus: ^4.0.1

    # Dependency injection
    get_it: ^7.6.0
    injectable: ^2.1.2

    # Navigation
    auto_route: ^7.6.0

    # State management
    bloc: ^8.1.2
    equatable: ^2.0.5
    flutter_bloc: ^8.1.3

    # User interface
    flutter_svg: ^2.0.7
    overlay_support: ^2.1.0
    flutter_screenutil: ^5.8.4
    flutter_markdown: ^0.6.15+1
    flutterui_modifiers: ^0.3.1

    # Package information
    package_info_plus: ^4.0.2

dev_dependencies:
    # Linting
    flutter_lints: ^2.0.2

    # Code generation
    build_runner: ^2.4.6
    injectable_generator: ^2.1.6
    auto_route_generator: ^7.1.1

    # Publishing
    rename: ^2.1.1
    icons_launcher: ^2.1.2

flutter:
    uses-material-design: true
    generate: true

    fonts:
        - family: SF Pro Display
          fonts:
              - asset: fonts/SF-Pro-Display/SF-Pro-Display-Black.otf
              - asset: fonts/SF-Pro-Display/SF-Pro-Display-BlackItalic.otf
              - asset: fonts/SF-Pro-Display/SF-Pro-Display-Bold.otf
              - asset: fonts/SF-Pro-Display/SF-Pro-Display-BoldItalic.otf
              - asset: fonts/SF-Pro-Display/SF-Pro-Display-Heavy.otf
              - asset: fonts/SF-Pro-Display/SF-Pro-Display-HeavyItalic.otf
              - asset: fonts/SF-Pro-Display/SF-Pro-Display-Light.otf
              - asset: fonts/SF-Pro-Display/SF-Pro-Display-LightItalic.otf
              - asset: fonts/SF-Pro-Display/SF-Pro-Display-Medium.otf
              - asset: fonts/SF-Pro-Display/SF-Pro-Display-MediumItalic.otf
              - asset: fonts/SF-Pro-Display/SF-Pro-Display-Regular.otf
              - asset: fonts/SF-Pro-Display/SF-Pro-Display-RegularItalic.otf
              - asset: fonts/SF-Pro-Display/SF-Pro-Display-Semibold.otf
              - asset: fonts/SF-Pro-Display/SF-Pro-Display-SemiboldItalic.otf
              - asset: fonts/SF-Pro-Display/SF-Pro-Display-Thin.otf
              - asset: fonts/SF-Pro-Display/SF-Pro-Display-ThinItalic.otf
              - asset: fonts/SF-Pro-Display/SF-Pro-Display-Ultralight.otf
              - asset: fonts/SF-Pro-Display/SF-Pro-Display-UltralightItalic.otf
    assets:
        - assets/images/img.png